package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer id;
     private Patrocinador patrocinador;
     private String titulo;
     private Date fechaInicio;
     private Date fechaFin;
     private String descripcion;
     private String contenidoMultimedia;
     private float cuantia;

    public Anuncio() {
    }

	
    public Anuncio(Patrocinador patrocinador, String titulo, Date fechaInicio, String descripcion, float cuantia) {
        this.patrocinador = patrocinador;
        this.titulo = titulo;
        this.fechaInicio = fechaInicio;
        this.descripcion = descripcion;
        this.cuantia = cuantia;
    }
    public Anuncio(Patrocinador patrocinador, String titulo, Date fechaInicio, Date fechaFin, String descripcion, String contenidoMultimedia, float cuantia) {
       this.patrocinador = patrocinador;
       this.titulo = titulo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.descripcion = descripcion;
       this.contenidoMultimedia = contenidoMultimedia;
       this.cuantia = cuantia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Patrocinador getPatrocinador() {
        return this.patrocinador;
    }
    
    public void setPatrocinador(Patrocinador patrocinador) {
        this.patrocinador = patrocinador;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getContenidoMultimedia() {
        return this.contenidoMultimedia;
    }
    
    public void setContenidoMultimedia(String contenidoMultimedia) {
        this.contenidoMultimedia = contenidoMultimedia;
    }
    public float getCuantia() {
        return this.cuantia;
    }
    
    public void setCuantia(float cuantia) {
        this.cuantia = cuantia;
    }




}


