package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String nombre;
     private String colorBorde;
     private String colorFondo;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombre, String colorFondo) {
        this.nombre = nombre;
        this.colorFondo = colorFondo;
    }
    public Categoria(String nombre, String colorBorde, String colorFondo, Set productos) {
       this.nombre = nombre;
       this.colorBorde = colorBorde;
       this.colorFondo = colorFondo;
       this.productos = productos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColorBorde() {
        return this.colorBorde;
    }
    
    public void setColorBorde(String colorBorde) {
        this.colorBorde = colorBorde;
    }
    public String getColorFondo() {
        return this.colorFondo;
    }
    
    public void setColorFondo(String colorFondo) {
        this.colorFondo = colorFondo;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


