package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cupon generated by hbm2java
 */
public class Cupon  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String codigo;
     private Date fechaPublicado;
     private Date fechaVencimiento;
     private String descripcion;

    public Cupon() {
    }

	
    public Cupon(String nombre, String codigo, Date fechaPublicado, String descripcion) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.fechaPublicado = fechaPublicado;
        this.descripcion = descripcion;
    }
    public Cupon(String nombre, String codigo, Date fechaPublicado, Date fechaVencimiento, String descripcion) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.fechaPublicado = fechaPublicado;
       this.fechaVencimiento = fechaVencimiento;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaPublicado() {
        return this.fechaPublicado;
    }
    
    public void setFechaPublicado(Date fechaPublicado) {
        this.fechaPublicado = fechaPublicado;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


