package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Patrocinador generated by hbm2java
 */
public class Patrocinador  implements java.io.Serializable {


     private String cif;
     private String nombre;
     private Set anuncios = new HashSet(0);

    public Patrocinador() {
    }

	
    public Patrocinador(String cif, String nombre) {
        this.cif = cif;
        this.nombre = nombre;
    }
    public Patrocinador(String cif, String nombre, Set anuncios) {
       this.cif = cif;
       this.nombre = nombre;
       this.anuncios = anuncios;
    }
   
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


