package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Tienda tienda;
     private Usuario usuario;
     private String enlace;
     private float precioOriginal;
     private String nombre;
     private Date fechaPublicado;
     private Date fechaVencimiento;
     private float precioDescuento;
     private String descripcion;
     private String imagen;
     private Set puntuas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Usuario usuario, String enlace, float precioOriginal, String nombre, Date fechaPublicado, float precioDescuento, String descripcion, String imagen) {
        this.usuario = usuario;
        this.enlace = enlace;
        this.precioOriginal = precioOriginal;
        this.nombre = nombre;
        this.fechaPublicado = fechaPublicado;
        this.precioDescuento = precioDescuento;
        this.descripcion = descripcion;
        this.imagen = imagen;
    }
    public Producto(Categoria categoria, Tienda tienda, Usuario usuario, String enlace, float precioOriginal, String nombre, Date fechaPublicado, Date fechaVencimiento, float precioDescuento, String descripcion, String imagen, Set puntuas) {
       this.categoria = categoria;
       this.tienda = tienda;
       this.usuario = usuario;
       this.enlace = enlace;
       this.precioOriginal = precioOriginal;
       this.nombre = nombre;
       this.fechaPublicado = fechaPublicado;
       this.fechaVencimiento = fechaVencimiento;
       this.precioDescuento = precioDescuento;
       this.descripcion = descripcion;
       this.imagen = imagen;
       this.puntuas = puntuas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEnlace() {
        return this.enlace;
    }
    
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }
    public float getPrecioOriginal() {
        return this.precioOriginal;
    }
    
    public void setPrecioOriginal(float precioOriginal) {
        this.precioOriginal = precioOriginal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaPublicado() {
        return this.fechaPublicado;
    }
    
    public void setFechaPublicado(Date fechaPublicado) {
        this.fechaPublicado = fechaPublicado;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public float getPrecioDescuento() {
        return this.precioDescuento;
    }
    
    public void setPrecioDescuento(float precioDescuento) {
        this.precioDescuento = precioDescuento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getPuntuas() {
        return this.puntuas;
    }
    
    public void setPuntuas(Set puntuas) {
        this.puntuas = puntuas;
    }




}


