package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1



/**
 * Puntua generated by hbm2java
 */
public class Puntua  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private Usuario usuario;
     private int puntuacion;

    public Puntua() {
    }

    public Puntua(Producto producto, Usuario usuario, int puntuacion) {
       this.producto = producto;
       this.usuario = usuario;
       this.puntuacion = puntuacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }




}


