package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tienda generated by hbm2java
 */
public class Tienda  implements java.io.Serializable {


     private String nombre;
     private String logo;
     private Set productos = new HashSet(0);

    public Tienda() {
    }

	
    public Tienda(String nombre, String logo) {
        this.nombre = nombre;
        this.logo = logo;
    }
    public Tienda(String nombre, String logo, Set productos) {
       this.nombre = nombre;
       this.logo = logo;
       this.productos = productos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


