package pojos;
// Generated 06-may-2020 12:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String email;
     private String hash;
     private String foto;
     private String tipo;
     private Set puntuas = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set productos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String email, String hash, String tipo) {
        this.usuario = usuario;
        this.email = email;
        this.hash = hash;
        this.tipo = tipo;
    }
    public Usuario(String usuario, String email, String hash, String foto, String tipo, Set puntuas, Set comentarios, Set productos) {
       this.usuario = usuario;
       this.email = email;
       this.hash = hash;
       this.foto = foto;
       this.tipo = tipo;
       this.puntuas = puntuas;
       this.comentarios = comentarios;
       this.productos = productos;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPuntuas() {
        return this.puntuas;
    }
    
    public void setPuntuas(Set puntuas) {
        this.puntuas = puntuas;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


